# This file was generated by GoReleaser. DO NOT EDIT.
cask "chaski@0.5.1" do
  version "0.5.1"

  on_macos do
    on_arm do
      sha256 "5f14b55e028bdaa0e4001eacb6f0cdcc00ad3579c20d72fd64848ee0d275303a"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0ce81e21a649cbd9c7fab8a16e67b82dc198833b325a4883b5ca13a26eac581b"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e06a5ef34c1f1a1439e553ad0b41ca191705313d240f7ef17067d009bdbbe2c4"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5528adec9a447d97a137979ed087bf03b4a18aa03654fef2b60568fc365daec5"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_amd64.tar.gz"
    end
  end

  name "chaski@0.5.1"
  desc "Small, stateless webhook-to-notification relay"
  homepage "https://github.com/home-operations/chaski"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chaski"

  preflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chaski"] if OS.mac?
  end

  generate_completions_from_executable "chaski",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
