# This file was generated by GoReleaser. DO NOT EDIT.
cask "chaski@0.3.1" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "ae1997fa7347bdc8aaf31d38f8a2183d82093eefcda5da09f679bc91287d854f"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "15deb2072c33cf150377957f2e4b5617ea9d4c5a82eada08ffd96dc3a93d51a3"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "defd39c6ebb45a8a341587c55ffe685412ea0a6ef0bc9b36019a1362cd1ad0c6"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6c35197c27778390e5c0251676e3ae3faae3ec01a63b765fe55d9ac9ec282f6e"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chaski@0.3.1"
  desc "Small, stateless webhook-to-notification relay"
  homepage "https://github.com/home-operations/chaski"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chaski"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chaski"] if OS.mac?
  end
  generate_completions_from_executable "chaski",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
