# This file was generated by GoReleaser. DO NOT EDIT.
cask "chaski@0.4" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "f2ccfd875109e335b83ddf86a9413ff5930a1cf17bec835f3134a73994c1f20a"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "28ecfb5bdf6ad56d59724bfeb0a382b5b704c9063c2bff38d369a07b700f10f5"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d4b9d1524c636ee785283eb8b5037bd9339ee7eb14183bca43958f59261c67c5"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "321dd5c858bc56d8b7174adf561e5905d4076b95e17858074f044ed2cc027a40"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chaski@0.4"
  desc "Small, stateless webhook-to-notification relay"
  homepage "https://github.com/home-operations/chaski"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chaski"

  preflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chaski"] if OS.mac?
  end

  generate_completions_from_executable "chaski",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
