# This file was generated by GoReleaser. DO NOT EDIT.
cask "chaski" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "972730f78d5481aff3ac85ab44d7c5745ca4ae14fb0d39f62e53773ef76b8793"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "943c072fd943eabf513e1bf5c629365428447d6702b7cdca4bcbab292be82ebd"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "120096288bcc806a0038e460ff8ed8a0021f49e689c4838248d0d2b8b289b3a7"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "12ae53a01e7800623d0de4290f84ff52a9a2a0c858501caa67707db0725f2d16"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chaski"
  desc "Small, stateless webhook-to-notification relay"
  homepage "https://github.com/home-operations/chaski"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chaski"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chaski"] if OS.mac?
  end
  generate_completions_from_executable "chaski",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
