# This file was generated by GoReleaser. DO NOT EDIT.
cask "chaski" do
  version "0.2.5"

  on_macos do
    on_intel do
      sha256 "c73073ef61b22fd46edc5fb3ab75798335ff23f707f002d8a716adc171d0a4b9"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa177b24fe0a5534a35a835b8aab2b676dea1fe3ab92419918c63f9818df7154"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c6c0f8b2e47df15b761a2c23998bb793b93c3a618f323cbaaa228abe8253758f"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fc0210069b569b77ef1987cedea6bd3d961ff8140c3f6b7d15e4e6dc138a717e"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chaski"
  desc "Small, stateless webhook-to-notification relay"
  homepage "https://github.com/home-operations/chaski"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chaski"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chaski"] if OS.mac?
  end
  generate_completions_from_executable "chaski",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
