# This file was generated by GoReleaser. DO NOT EDIT.
cask "chaski" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "d5e834d812140dd97d64c58b1ce5c89df6ad43b5b59f5a46665c4d5a3156fd98"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b0bdf39603a4fa1e0d8e738c7f1d97b861add0a5616f622e36660e5b65b0cb99"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "42ead5503391ec0330befeda8755b01c605eee042739fd48071a37509fcc4afd"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "78c5b6b1f181c91d258d3e3163e9bc15f7940627366c1d4e3c1b96eccd947dc9"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chaski"
  desc "Small, stateless webhook-to-notification relay"
  homepage "https://github.com/home-operations/chaski"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chaski"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chaski"] if OS.mac?
  end

  # No zap stanza required

end
