# This file was generated by GoReleaser. DO NOT EDIT.
cask "chaski@0.3" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "43805ca63ee9d240bece71c0bc66bfa849bd79a42f9c8f71d36bef7e9a9a5caa"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "35a64405839fd051fc79cd7744bdb8f85d7bef08d07dd10075e377f182c3e7e2"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "db2be42fd878386c6bd5ab39dd3086854c365426fe98afef66d17a97e5159c3f"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "83a421c895f179a6e7e8629d2d6a23660a25feefc2034fa21b9f27dd17bf55f7"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chaski@0.3"
  desc "Small, stateless webhook-to-notification relay"
  homepage "https://github.com/home-operations/chaski"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chaski"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chaski"] if OS.mac?
  end
  generate_completions_from_executable "chaski",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
