# This file was generated by GoReleaser. DO NOT EDIT.
cask "chaski@0.4" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "a8475effb33dffadc356a537da55a17ae5400dd144b43a65397b6e8792620cc3"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a377d8b85fbe190b805d4db96553e737004b29daa11fc9e6b604a64389201fe3"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e1686860a974e8f060a1944e4d482c591bb2c4fd9590e1943daaafc52bd1de7a"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "842e822d075beefd49138311b2747e5804fd1c6d051b5d61d0a7d96f55dbfea3"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chaski@0.4"
  desc "Small, stateless webhook-to-notification relay"
  homepage "https://github.com/home-operations/chaski"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chaski"

  preflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chaski"] if OS.mac?
  end

  generate_completions_from_executable "chaski",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
