# This file was generated by GoReleaser. DO NOT EDIT.
cask "chaski@0.5" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "230051e6bebdc6f1081a552125a35b060b57e581c068a61af8fcf7e2ddf3c1a2"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "efaac01b269757be89cdf9b16a52b2a18cb4ebf56a050e5e3bc74ae82a88e285"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c6aec3e15535b955fe5890f5a51423814308147d427d0fc7104e0cbe58b76e3b"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "32dcbb942d00caf98f5f09329b21ee297557b8a3a3bb3f818f8359245de4331e"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chaski@0.5"
  desc "Small, stateless webhook-to-notification relay"
  homepage "https://github.com/home-operations/chaski"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chaski"

  preflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chaski"] if OS.mac?
  end

  generate_completions_from_executable "chaski",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
