# This file was generated by GoReleaser. DO NOT EDIT.
cask "chaski@0.3.0" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "b2a16fd3e222b6f4874abdd4b0c2ce5adbfa00d5f4424d9b33804f80f36c8cd5"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "97eac4e72f89849f2fee5cab4c9f1ccea5e0b3c09142dfd5d13c437d05323d4e"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1e1259fda31ed01fb823e82959ea932c4a7e53c81b3d54070d6c0825d669ae2b"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e81295f024af752d09bb997aa980029f2ed52b00d04734b7480e962d62db0004"
      url "https://github.com/home-operations/chaski/releases/download/#{version}/chaski_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chaski@0.3.0"
  desc "Small, stateless webhook-to-notification relay"
  homepage "https://github.com/home-operations/chaski"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chaski"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chaski"] if OS.mac?
  end
  generate_completions_from_executable "chaski",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
