# This file was generated by GoReleaser. DO NOT EDIT.
cask "flate@0.6.4" do
  version "0.6.4"

  on_macos do
    on_arm do
      sha256 "285a6f5e76900d4d8a2ae8e161e4e0e13f8e4d6f4e3929dc387ad663a9ceb1db"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "35350ea0c61bb2539cc66ee0bb868b0329f5e73619178783f32dbb829b308de1"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "42e79f5936dbdba83f5c356ba1a0091f236600fdb2f75b2de71f9f8d28bec43e"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ad64459f346d7ba097e828d0b797b168d3764f7b0dc75e0853018a92b5755937"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_amd64.tar.gz"
    end
  end

  name "flate@0.6.4"
  desc "Render and diff Flux GitOps repositories offline, without a cluster"
  homepage "https://github.com/home-operations/flate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flate"

  preflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flate"] if OS.mac?
  end

  generate_completions_from_executable "flate",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
