# This file was generated by GoReleaser. DO NOT EDIT.
cask "flate@0.5" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "54ca280064475005c42421559920c05ab9fdef2643d14db61cd1fbc5ee660c6a"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "455dd29fd61e1149f12331b806a5ec5351b832583cc86020022a8037b453ec2f"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "89345d92239289754ac0217d09878c24c1fdce71eadfb0bc551aa8843d1675fb"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d8df4919f41793bac5b6f2fadd6f3562e5ff145399a5b0029457cc2e5d820283"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flate@0.5"
  desc "Render and diff Flux GitOps repositories offline, without a cluster"
  homepage "https://github.com/home-operations/flate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flate"

  preflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flate"] if OS.mac?
  end

  generate_completions_from_executable "flate",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
