# This file was generated by GoReleaser. DO NOT EDIT.
cask "flate@0.4.11" do
  version "0.4.11"

  on_macos do
    on_intel do
      sha256 "a916d0718cae568d281c45bd3b9be9acf5e42fbbb810d2e64b94cadefa9980f8"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2dbf422eec6b79922dd21c8336c2142b48bccab39894ee99d67b0e932bb7c531"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3770784f978c4f88ffb9691f816e6c53421e45c8377efd161b023ff6e08fa78c"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4eb4b41edd41a8972fbf3b4ce9682e0fddbf5d1ac3d9697a0f91749c9d5f18c2"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flate@0.4.11"
  desc "Render and diff Flux GitOps repositories offline, without a cluster"
  homepage "https://github.com/home-operations/flate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flate"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flate"] if OS.mac?
  end
  generate_completions_from_executable "flate",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
