# This file was generated by GoReleaser. DO NOT EDIT.
cask "flate" do
  version "0.1.26"

  on_macos do
    on_intel do
      sha256 "22d607e0a5b87927d46f3259d0f574c1356f5e83f05d80f64f8161d93680a0a9"
      url "https://github.com/home-operations/flate/releases/download/#{version}/flate_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "02d4d640409b29bb830b6cd31405b9d14ac66ca3da4c2ae4aaa5f05e726cbcb5"
      url "https://github.com/home-operations/flate/releases/download/#{version}/flate_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "963f5c79ce7998b96d60ed89b78a5aaa7e06c8eee24c4c384c017882fbb240e8"
      url "https://github.com/home-operations/flate/releases/download/#{version}/flate_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e17c5e6386a6f8224aaeab4a383674d03b1708ca0b9c420a95740fba234bf29c"
      url "https://github.com/home-operations/flate/releases/download/#{version}/flate_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flate"
  desc "Render and diff Flux GitOps repositories offline, without a cluster"
  homepage "https://github.com/home-operations/flate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flate"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flate"] if OS.mac?
  end
  generate_completions_from_executable "flate",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
