# This file was generated by GoReleaser. DO NOT EDIT.
cask "flate" do
  version "0.1.24"

  on_macos do
    on_intel do
      sha256 "f41b021df0651433288729b5edfbd646e4ed2d59edb5b5d77c20f0a16363a589"
      url "https://github.com/home-operations/flate/releases/download/#{version}/flate_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d8363fce58eaacc1cbe41095ab23a094011e1a930321bf5a2fb7f02a9c712371"
      url "https://github.com/home-operations/flate/releases/download/#{version}/flate_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5e595ce1993580cef8a66cbfc9c8d9ae7affe792598be8963c6ce611964b684f"
      url "https://github.com/home-operations/flate/releases/download/#{version}/flate_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d615718d15319400d710db5fa0b34f85e341b79b2cd40225a26a44d28eba484d"
      url "https://github.com/home-operations/flate/releases/download/#{version}/flate_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flate"
  desc "Render and diff Flux GitOps repositories offline, without a cluster"
  homepage "https://github.com/home-operations/flate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flate"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flate"] if OS.mac?
  end
  generate_completions_from_executable "flate",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
