# This file was generated by GoReleaser. DO NOT EDIT.
cask "flate@0.6" do
  version "0.6.5"

  on_macos do
    on_arm do
      sha256 "76274be5ef8b016e80ea0abf7b6f612adc76a89f7613d2e7f7e3550af5b9e186"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4b1dcefb4613b4c02f3374c8fc8d4082d42d893f4303daa16e24e37d58bccb78"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7f514814890df4a095887943ae606be1a8af878606b7bd0575efe75402cd38dc"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "37eb0cd91a6752340754375743aa616c263cd8367ce594abd42ee955e1ec0099"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_amd64.tar.gz"
    end
  end

  name "flate@0.6"
  desc "Render and diff Flux GitOps repositories offline, without a cluster"
  homepage "https://github.com/home-operations/flate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flate"

  preflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flate"] if OS.mac?
  end

  generate_completions_from_executable "flate",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
