# This file was generated by GoReleaser. DO NOT EDIT.
cask "flate@0.6" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "8ea1dbb4d296047758fb94a877251ecc20c88326e49027d0e4c4ba74d8596cd4"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3ce7750365ad59b21f9865a33cd1a1947d1a11a3f2abfe565a5ea591c798fcca"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ae3bb7372b34cfa18cabae6b3d4e65ac5c473f422c296d0d589074299f358c24"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0edd48e734b3073ea592aeff0307e6e6e88c4d644d49da088a735b5c720a4a93"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flate@0.6"
  desc "Render and diff Flux GitOps repositories offline, without a cluster"
  homepage "https://github.com/home-operations/flate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flate"

  preflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flate"] if OS.mac?
  end

  generate_completions_from_executable "flate",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
