# This file was generated by GoReleaser. DO NOT EDIT.
cask "flate@0.4.14" do
  version "0.4.14"

  on_macos do
    on_intel do
      sha256 "7cd179ddb7fd4699ce5715bfacab7bc1a78a9bc07c884b691e05ef978846c8de"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "94dd5847ed6849ac4187612b16e100970c157498baf1f8f7ec2bf5ca8ab866da"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1d5381c5550593025c7109ea92bb261cd01cccf7eb608a78db6f3fbbef0dab16"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0fd29e5c7ed81686cac2c7e0233f8947ceade3a5b717b38a3349629beba18f57"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flate@0.4.14"
  desc "Render and diff Flux GitOps repositories offline, without a cluster"
  homepage "https://github.com/home-operations/flate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flate"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flate"] if OS.mac?
  end
  generate_completions_from_executable "flate",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
