# This file was generated by GoReleaser. DO NOT EDIT.
cask "flate@0.4" do
  version "0.4.12"

  on_macos do
    on_intel do
      sha256 "1627aa0bedb96ec6ff016429ee7c6fbeb4517e5c9d4adb734ebf2926245cf9b5"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4de0259199b33dcfa36b435a5f00de405b7f81ef01576e68c07599dd651b0d85"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "85e76d6a47f194efef89b1bf12ac108bfbce3e29fde893e8e76b977ab286c5ac"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd047cf122220ef6e798a6ad1d7c5307d183b981b36c5120141e945a1cd2b5aa"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flate@0.4"
  desc "Render and diff Flux GitOps repositories offline, without a cluster"
  homepage "https://github.com/home-operations/flate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flate"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flate"] if OS.mac?
  end
  generate_completions_from_executable "flate",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
