# This file was generated by GoReleaser. DO NOT EDIT.
cask "flate" do
  version "0.1.19"

  on_macos do
    on_intel do
      sha256 "4a7617aa3cac581d56537e1a41b3c038b0c6d53b2d5a2dadb5a0a772f7f9811d"
      url "https://github.com/home-operations/flate/releases/download/#{version}/flate_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "72b83fa30fb42ad26dabd3e434ef72a5648f02d5ef053cbc4de959b22bb192cd"
      url "https://github.com/home-operations/flate/releases/download/#{version}/flate_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b3b7296ac5762dc9fe9ba83802221a374a0e62fe945065ae41dfd75625a3799d"
      url "https://github.com/home-operations/flate/releases/download/#{version}/flate_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f8928e1474a48a444bae52c29cd3e4fca3c6bfc9783192a2606b78a5f51c4a44"
      url "https://github.com/home-operations/flate/releases/download/#{version}/flate_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flate"
  desc "Render and diff Flux GitOps repositories offline, without a cluster"
  homepage "https://github.com/home-operations/flate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flate"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flate"] if OS.mac?
  end

  # No zap stanza required

end
