# This file was generated by GoReleaser. DO NOT EDIT.
cask "flate@0.6.2" do
  version "0.6.2"

  on_macos do
    on_arm do
      sha256 "21c883ccf9adcf0a6bbb143ad07dcaa1bd96dd230df486f72b7810126467f9b9"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5bae9a9fcc0c8aaad11c4e2c07856f92d68d45f23a2d098dd0b3912517eb693"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eb55ff9e718327aedbed82bd57eb8694b4dd7dcdf7573b68344bc1b981f7a5d9"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "26475a469ec781c1a4ef4fba715c162c9e480549802cd6639e155cfe0e39f04a"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_amd64.tar.gz"
    end
  end

  name "flate@0.6.2"
  desc "Render and diff Flux GitOps repositories offline, without a cluster"
  homepage "https://github.com/home-operations/flate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flate"

  preflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flate"] if OS.mac?
  end

  generate_completions_from_executable "flate",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
