# This file was generated by GoReleaser. DO NOT EDIT.
cask "flate@0.6" do
  version "0.6.3"

  on_macos do
    on_arm do
      sha256 "3c72ecdf68b40230fbc15651ff25ad4941e3a2dc0d382d37c0ff1a7a719ebff7"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b22472d6a0c98072dfd6a9474a0b4900e7c0a039dd45b7892ec48c51652134c1"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "690140938d104fea4742f51d1a5d3869af653101f1965ea1534f6e79f8740349"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3a0e6ac1234cb995285280de88dd822e2d26b275765af1e5fc72f71a10bd34ad"
      url "https://github.com/home-operations/flate/releases/download/v#{version}/flate_#{version}_linux_amd64.tar.gz"
    end
  end

  name "flate@0.6"
  desc "Render and diff Flux GitOps repositories offline, without a cluster"
  homepage "https://github.com/home-operations/flate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flate"

  preflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flate"] if OS.mac?
  end

  generate_completions_from_executable "flate",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
