# This file was generated by GoReleaser. DO NOT EDIT.
cask "kopiur" do
  version "0.9.3"

  on_macos do
    on_intel do
      sha256 "726e528c8e4038b5561a8bf0b80692dda2f2f2a6b695af60075046474662c413"
      url "https://github.com/home-operations/kopiur/releases/download/#{version}/kubectl-kopiur_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "74e043537133e80c870c561ad20cc073a17b7658814c54cb5edc52e200d23836"
      url "https://github.com/home-operations/kopiur/releases/download/#{version}/kubectl-kopiur_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4c73a3c29b833c6d0ef3c24d4bf62c9dc61000498d3583a1505ac60c4c17d9be"
      url "https://github.com/home-operations/kopiur/releases/download/#{version}/kubectl-kopiur_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "978337fa8938c4192e217973be5beead5e6fa89c8dcd9c139d30950c81109f0f"
      url "https://github.com/home-operations/kopiur/releases/download/#{version}/kubectl-kopiur_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kopiur"
  desc "Kubectl plugin operating the kopiur Kopia-native backup operator"
  homepage "https://kopiur.home-operations.com/cli/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kopiur"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kopiur"] if OS.mac?
  end

  # No zap stanza required

end
