# This file was generated by GoReleaser. DO NOT EDIT.
cask "kopiur" do
  version "0.10.3"

  on_macos do
    on_intel do
      sha256 "129a2d6143bcf3bae0dc670e9bab4cfb3976893d0907453e602241940f79c058"
      url "https://github.com/home-operations/kopiur/releases/download/#{version}/kubectl-kopiur_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "097fb2b1ab6ff1bf449fbc3beb142d6e254b6d2f870c4376e53ae0e40051996a"
      url "https://github.com/home-operations/kopiur/releases/download/#{version}/kubectl-kopiur_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1935f0177e1db5950105c04c07680d335bb7ccd2eca4b615b00c164b9101a530"
      url "https://github.com/home-operations/kopiur/releases/download/#{version}/kubectl-kopiur_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0b6c1562e999bdeaa7d3b411df53bb180641d4b75b436c4617cb14c000e14207"
      url "https://github.com/home-operations/kopiur/releases/download/#{version}/kubectl-kopiur_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kopiur"
  desc "Kubectl plugin operating the kopiur Kopia-native backup operator"
  homepage "https://kopiur.home-operations.com/cli/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kopiur"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kopiur"] if OS.mac?
  end

  # No zap stanza required

end
