# This file was generated by GoReleaser. DO NOT EDIT.
cask "kopiur" do
  version "0.8.1"

  on_macos do
    on_intel do
      sha256 "ecebfdf5164c03d173ae70c08fb0940c2cefa7a06b798875c125761000f9a7a6"
      url "https://github.com/home-operations/kopiur/releases/download/#{version}/kubectl-kopiur_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "345de4a877eace193d309f64694cf638c0a1e828fa1933c46288094c06b13ef2"
      url "https://github.com/home-operations/kopiur/releases/download/#{version}/kubectl-kopiur_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "952fc93080a4357105af97cfc53ac5bd70b2eba414065db5dd8fcacd0575962b"
      url "https://github.com/home-operations/kopiur/releases/download/#{version}/kubectl-kopiur_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "791133cbc4b6368c3a2ea0350a7411995daa93f8ecfbbf6570a511ed86fdf7ba"
      url "https://github.com/home-operations/kopiur/releases/download/#{version}/kubectl-kopiur_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kopiur"
  desc "Kubectl plugin operating the kopiur Kopia-native backup operator"
  homepage "https://kopiur.home-operations.com/cli/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kopiur"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kopiur"] if OS.mac?
  end

  # No zap stanza required

end
