# This file was generated by GoReleaser. DO NOT EDIT.
cask "yamlls" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "a1823e3a3a62711b01cecfe6d85ec48c1c1df0e8a375870d1fa4588d28628774"
      url "https://github.com/home-operations/yamlls/releases/download/#{version}/yamlls_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bba96b65fb7b20b072372739a6eab0dbdcb71f3478a9991bd9a1b7210db1a00c"
      url "https://github.com/home-operations/yamlls/releases/download/#{version}/yamlls_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "90af8b7758d836478d71ab725a4da9fafd8048e6d9eb00c9e76acfddf66614c5"
      url "https://github.com/home-operations/yamlls/releases/download/#{version}/yamlls_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "855a6b792bcea9df8cb7f027006652a099e902d08735b6ffc9489b78a6fe5132"
      url "https://github.com/home-operations/yamlls/releases/download/#{version}/yamlls_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yamlls"
  desc "YAML language server with pluggable rendering for Flux sources."
  homepage "https://github.com/home-operations/yamlls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yamlls"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yamlls"] if OS.mac?
  end

  # No zap stanza required

end
