# This file was generated by GoReleaser. DO NOT EDIT.
cask "yamlls" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "5c30a51e48fbed9dda3cf8936893eab0b5454141753ab95bad29317b30ab38b2"
      url "https://github.com/home-operations/yamlls/releases/download/#{version}/yamlls_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "62afacf8034852d1c8547653e7faa38ff626405fe1bd4cbe2011b8c6379095fe"
      url "https://github.com/home-operations/yamlls/releases/download/#{version}/yamlls_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "33ef6091c9b640cfe4168abe38b07c10171ba0ac716a83fb468ab28d84342dee"
      url "https://github.com/home-operations/yamlls/releases/download/#{version}/yamlls_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e7cb47e6bf49567b2c07953302aa602a025dd0b4170c96d3b61fdf0b1eed6d0"
      url "https://github.com/home-operations/yamlls/releases/download/#{version}/yamlls_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yamlls"
  desc "YAML language server with pluggable rendering for Flux sources."
  homepage "https://github.com/home-operations/yamlls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yamlls"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yamlls"] if OS.mac?
  end

  # No zap stanza required

end
