# This file was generated by GoReleaser. DO NOT EDIT.
cask "yamlls" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "8671eedc7cefd950e2364e322f9033e2a023be3dbedbdd678c4d273a44af6d17"
      url "https://github.com/home-operations/yamlls/releases/download/#{version}/yamlls_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "261cd603dadeb45991244ef1451fdb314306bda038dc7994f389493494a80e81"
      url "https://github.com/home-operations/yamlls/releases/download/#{version}/yamlls_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "411cdbfc1edd17f3f4bd7a882fa87105f407ccf104b9655de68ebe04aa053334"
      url "https://github.com/home-operations/yamlls/releases/download/#{version}/yamlls_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fc58d01253d1ffbde50f590c660398a2acb481cd19cfa6aa09d362be795769fa"
      url "https://github.com/home-operations/yamlls/releases/download/#{version}/yamlls_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yamlls"
  desc "YAML language server with pluggable rendering for Flux sources."
  homepage "https://github.com/home-operations/yamlls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yamlls"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yamlls"] if OS.mac?
  end

  # No zap stanza required

end
