# This file was generated by GoReleaser. DO NOT EDIT.
cask "yayamlls" do
  version "0.3.2"

  on_macos do
    on_arm do
      sha256 "a13a9266bc084b3dd6248691e70b9fc6bf3c04ebdac0219a32c8ff6dcbdde331"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2532b3a6dc689a1594b93092a83946616504edc8685dd20e78151eb5e2c5153e"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fc1399b8af2dc5fb11bb5b2c4c8ba35499766f3e5f2a5756d267d5ed77bb12fb"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f6dfd7aa573e46a37a0595ff9139eab8f76eae9af179617a4fcb5d707ecb4fe3"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_linux_amd64.tar.gz"
    end
  end

  name "yayamlls"
  desc "YAML language server with pluggable rendering for Flux sources."
  homepage "https://github.com/home-operations/yayamlls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yayamlls"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yayamlls"] if OS.mac?
  end

  # No zap stanza required
end
