# This file was generated by GoReleaser. DO NOT EDIT.
cask "yayamlls@0.1" do
  version "0.1.14"

  on_macos do
    on_intel do
      sha256 "d1fa3f46159632f42a08bd303b3307551fdbf6fa73af00eb5841d572b510a841"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f4a846603e25c3e5d61839758cea1671da98e23d236d9cd82530bf31b795dfa"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8e742e78c973fa05702e303a26d46ddac5bdbf8a040ce59ef24f22665aa5b3e5"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c60b0da0b6c4db93c8bbeefeedcb80a02fdedfb7b61c3eadea3e56eff37ca8c6"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yayamlls@0.1"
  desc "YAML language server with pluggable rendering for Flux sources."
  homepage "https://github.com/home-operations/yayamlls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yayamlls"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yayamlls"] if OS.mac?
  end

  # No zap stanza required

end
