# This file was generated by GoReleaser. DO NOT EDIT.
cask "yayamlls" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "b80c0b41b34b98fc0d687ddc2d7ad5603759afd2386d235925621fa83a5bed7b"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7d566c8057ff08d6fe6426c879109dfbe1070e54646f7d1c52f3e59c1dc2438b"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e6f414bebedd083823c7ad1a8e93af0486a88dd794a52fcb79a67b1de9bee878"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "32f2ef03efac5ef134c9ab97bb54dda927b970282f736e8aae4935cc4aed9ed0"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yayamlls"
  desc "YAML language server with pluggable rendering for Flux sources."
  homepage "https://github.com/home-operations/yayamlls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yayamlls"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yayamlls"] if OS.mac?
  end

  # No zap stanza required

end
