# This file was generated by GoReleaser. DO NOT EDIT.
cask "yayamlls" do
  version "0.1.7"

  on_macos do
    on_intel do
      sha256 "1314d36d6ebe619c59fea0dc1951a83552933e8211dbcb6c41f597f1a3a2e6ca"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1f982ae681a4f658e55e6dfde2c4f4f496d5cb979f50b354a55246cfe262e5f3"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f14ebb22f174eb7b15776e91f5acdbeb83283a8bf190ae168225a2bf1a4d6acb"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a937bcc092c695620df51057821c3b0cac09011c12d10f9a2be7d0c88aeea17"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yayamlls"
  desc "YAML language server with pluggable rendering for Flux sources."
  homepage "https://github.com/home-operations/yayamlls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yayamlls"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yayamlls"] if OS.mac?
  end

  # No zap stanza required

end
