# This file was generated by GoReleaser. DO NOT EDIT.
cask "yayamlls@0.3" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "7fdd604905260a33ed953f8887487a39ff612b3207e397e6784b91cdf2b62d9e"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4839ff46365fcf482713391f7bc5a2f137d43f6faa6c337fdb5ff84458103b2c"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c74b677003118799c8a5d679eb5898c8b823e376b9de28947943ddabcafc8380"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3fe1274d2e451ad97c08fc12a59536725092046d27ed767274cf11c597e3ad9d"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_linux_amd64.tar.gz"
    end
  end

  name "yayamlls@0.3"
  desc "YAML language server with pluggable rendering for Flux sources."
  homepage "https://github.com/home-operations/yayamlls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yayamlls"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yayamlls"] if OS.mac?
  end

  # No zap stanza required
end
