# This file was generated by GoReleaser. DO NOT EDIT.
cask "yayamlls@0.1.12" do
  version "0.1.12"

  on_macos do
    on_intel do
      sha256 "4a5ba9bd97acef843f658844a38573255d502ba98a5f07fa8304215f67404967"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "54f8b3afbadea5ee334e71431b38afb5e3732ec59110d7a3dd117881c0387b98"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "17a90c4d4af15306a4ed40f8afc72b6f0faa949b068da8e2572bf2a4563c49a9"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "35aaffe96749d483d3f100341bde614ba4274f6e94e30f60f3a4b65bd969fcff"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yayamlls@0.1.12"
  desc "YAML language server with pluggable rendering for Flux sources."
  homepage "https://github.com/home-operations/yayamlls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yayamlls"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yayamlls"] if OS.mac?
  end

  # No zap stanza required

end
