# This file was generated by GoReleaser. DO NOT EDIT.
cask "yayamlls@0.1" do
  version "0.1.15"

  on_macos do
    on_intel do
      sha256 "b413b185e050c2ba32667637a3f2b849d1cb67eb54d636fcda5bc0ae66026da6"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9ff4b0fd670c2e7dc6e93323d1cc28f2d9484daf8a430feaf84aa1c098bf2d6f"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "926e1d5a5da1e287ce8bc37d88f61e144f025d252107f572525e4c1185f845ed"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "27677322abbd55c2ce9c25e798b86ceb05d338a3aa1a1572ff720b3cf8b2a721"
      url "https://github.com/home-operations/yayamlls/releases/download/#{version}/yayamlls_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yayamlls@0.1"
  desc "YAML language server with pluggable rendering for Flux sources."
  homepage "https://github.com/home-operations/yayamlls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yayamlls"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yayamlls"] if OS.mac?
  end

  # No zap stanza required

end
